<?php
namespace app\admin\controller;

class Upload extends Common
{

    /**
     * @var \app\common\service\Upload
     * */
    private $uploadSer;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //实例化上传组件
        $this->uploadSer = new \app\common\service\Upload($this->user_id);
    }


    //获取上传凭证
    public function info($type='image',$accept='images')
    {
        try{
            $data=$this->uploadSer->info($type);
        }catch (\Exception $e){
            return '';
        }
        return json_encode(['url'=>$data['url'],'data'=>['token'=>$data['token'],'x:up_index'=>0],'accept'=>$accept]);

    }

    //获取上传凭证
    public function authorization()
    {
        try{
            $data=$this->uploadSer->handleVideoImg('/qn_image/20190726/10_5d3aa05fb7297.mp4');
        }catch (\Exception $e){
            return '';
        }
        return json_encode($data);

    }

    //上传
    public function upload($type='image')
    {
        try{
            $data = $this->uploadSer->upload($type);
        }catch (\Exception $e){
            return $this->_resData(0,$e->getMessage());
        }
        return $this->_resData(1,'获取成功',$data);

    }
}
